# Generated by Django 5.2.8 on 2025-11-19 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_user_order_created_ad_order_update_ad_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='update_ad',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AlterField(
            model_name='comment',
            name='update_ad',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='update_ad',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='update_ad',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
